"""
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

from functools import reduce


class Solution:
    """
    S-O(nlogn)
    T-O(n)
    """
    def findTheDifference(self, s: str, t: str) -> str:
        sorted_s = sorted(s)
        sorted_t = sorted(t)
        for i in range(len(sorted_s)):
            if sorted_s[i] != sorted_t[i]:
                print(1, sorted_t[i])
                return sorted_t[i]
        else:
            return sorted_t.pop()


class Solution1:
    """
    S-O(n)
    T-O(1)
    """
    def findTheDifference(self, s: str, t: str) -> str:
        s_sum = sum(ord(x) for x in s)
        t_sum = sum(ord(x) for x in t)
        return chr(t_sum - s_sum)

for sol in Solution1, Solution:
    assert sol().findTheDifference("abcd", "abcde") == "e"
    assert sol().findTheDifference("", "y") == "y"
